modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="forgecraft"
version="1.0"
displayName="ForgeCraft"
logoFile=""
credits="Me"
authors="NineCreators"
description='''
A large content mod for minecraft.
Github:

'''
[[dependencies.foorgecraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
